# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Prod deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - name: FTP Deploy
      # You may pin to the exact commit or the version.
      # uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        # ftp server
        server: ${{ secrets.DEPLOY_PROD_HOST }}
        # ftp username
        username: ${{ secrets.DEPLOY_PROD_USER }}
        # ftp password
        password: ${{ secrets.DEPLOY_PROD_PASSWORD }}
        # Folder to upload from, must end with trailing slash /
        local-dir: dist/
        # Path to upload to on the server. Must end with trailing slash /
        server-dir: ${{ secrets.DEPLOY_PROD_PATH }}
        dry-run: true 
